// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sokol111/ecommerce-catalog-service/internal/domain/product"
	"github.com/Sokol111/ecommerce-commons/pkg/persistence/mongo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id string) (*product.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *product.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*product.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *product.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(product1 *product.Product, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*product.Product, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindList provides a mock function for the type MockRepository
func (_mock *MockRepository) FindList(ctx context.Context, query product.ListQuery) (*mongo.PageResult[product.Product], error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for FindList")
	}

	var r0 *mongo.PageResult[product.Product]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, product.ListQuery) (*mongo.PageResult[product.Product], error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, product.ListQuery) *mongo.PageResult[product.Product]); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.PageResult[product.Product])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, product.ListQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindList'
type MockRepository_FindList_Call struct {
	*mock.Call
}

// FindList is a helper method to define mock.On call
//   - ctx context.Context
//   - query product.ListQuery
func (_e *MockRepository_Expecter) FindList(ctx interface{}, query interface{}) *MockRepository_FindList_Call {
	return &MockRepository_FindList_Call{Call: _e.mock.On("FindList", ctx, query)}
}

func (_c *MockRepository_FindList_Call) Run(run func(ctx context.Context, query product.ListQuery)) *MockRepository_FindList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 product.ListQuery
		if args[1] != nil {
			arg1 = args[1].(product.ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindList_Call) Return(pageResult *mongo.PageResult[product.Product], err error) *MockRepository_FindList_Call {
	_c.Call.Return(pageResult, err)
	return _c
}

func (_c *MockRepository_FindList_Call) RunAndReturn(run func(ctx context.Context, query product.ListQuery) (*mongo.PageResult[product.Product], error)) *MockRepository_FindList_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository) Insert(ctx context.Context, product1 *product.Product) error {
	ret := _mock.Called(ctx, product1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *product.Product) error); ok {
		r0 = returnFunc(ctx, product1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - product1 *product.Product
func (_e *MockRepository_Expecter) Insert(ctx interface{}, product1 interface{}) *MockRepository_Insert_Call {
	return &MockRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, product1)}
}

func (_c *MockRepository_Insert_Call) Run(run func(ctx context.Context, product1 *product.Product)) *MockRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *product.Product
		if args[1] != nil {
			arg1 = args[1].(*product.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call) Return(err error) *MockRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, product1 *product.Product) error) *MockRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, product1 *product.Product) (*product.Product, error) {
	ret := _mock.Called(ctx, product1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *product.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *product.Product) (*product.Product, error)); ok {
		return returnFunc(ctx, product1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *product.Product) *product.Product); ok {
		r0 = returnFunc(ctx, product1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *product.Product) error); ok {
		r1 = returnFunc(ctx, product1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product1 *product.Product
func (_e *MockRepository_Expecter) Update(ctx interface{}, product1 interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, product1)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, product1 *product.Product)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *product.Product
		if args[1] != nil {
			arg1 = args[1].(*product.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(product11 *product.Product, err error) *MockRepository_Update_Call {
	_c.Call.Return(product11, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, product1 *product.Product) (*product.Product, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
