// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sokol111/ecommerce-catalog-service/internal/domain/attribute"
	"github.com/Sokol111/ecommerce-commons/pkg/persistence/mongo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockRepository
func (_mock *MockRepository) Exists(ctx context.Context, id string) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockRepository_Exists_Call {
	return &MockRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockRepository_Exists_Call) Run(run func(ctx context.Context, id string)) *MockRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Exists_Call) Return(b bool, err error) *MockRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, error)) *MockRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id string) (*attribute.Attribute, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *attribute.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*attribute.Attribute, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *attribute.Attribute); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*attribute.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(attribute1 *attribute.Attribute, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(attribute1, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*attribute.Attribute, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByIDs(ctx context.Context, ids []string) ([]*attribute.Attribute, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*attribute.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*attribute.Attribute, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*attribute.Attribute); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*attribute.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRepository_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockRepository_FindByIDs_Call {
	return &MockRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByIDs_Call) Return(attributes []*attribute.Attribute, err error) *MockRepository_FindByIDs_Call {
	_c.Call.Return(attributes, err)
	return _c
}

func (_c *MockRepository_FindByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string) ([]*attribute.Attribute, error)) *MockRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDsOrFail provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByIDsOrFail(ctx context.Context, ids []string) ([]*attribute.Attribute, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDsOrFail")
	}

	var r0 []*attribute.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*attribute.Attribute, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*attribute.Attribute); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*attribute.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByIDsOrFail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDsOrFail'
type MockRepository_FindByIDsOrFail_Call struct {
	*mock.Call
}

// FindByIDsOrFail is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRepository_Expecter) FindByIDsOrFail(ctx interface{}, ids interface{}) *MockRepository_FindByIDsOrFail_Call {
	return &MockRepository_FindByIDsOrFail_Call{Call: _e.mock.On("FindByIDsOrFail", ctx, ids)}
}

func (_c *MockRepository_FindByIDsOrFail_Call) Run(run func(ctx context.Context, ids []string)) *MockRepository_FindByIDsOrFail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByIDsOrFail_Call) Return(attributes []*attribute.Attribute, err error) *MockRepository_FindByIDsOrFail_Call {
	_c.Call.Return(attributes, err)
	return _c
}

func (_c *MockRepository_FindByIDsOrFail_Call) RunAndReturn(run func(ctx context.Context, ids []string) ([]*attribute.Attribute, error)) *MockRepository_FindByIDsOrFail_Call {
	_c.Call.Return(run)
	return _c
}

// FindList provides a mock function for the type MockRepository
func (_mock *MockRepository) FindList(ctx context.Context, query attribute.ListQuery) (*mongo.PageResult[attribute.Attribute], error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for FindList")
	}

	var r0 *mongo.PageResult[attribute.Attribute]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, attribute.ListQuery) (*mongo.PageResult[attribute.Attribute], error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, attribute.ListQuery) *mongo.PageResult[attribute.Attribute]); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.PageResult[attribute.Attribute])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, attribute.ListQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindList'
type MockRepository_FindList_Call struct {
	*mock.Call
}

// FindList is a helper method to define mock.On call
//   - ctx context.Context
//   - query attribute.ListQuery
func (_e *MockRepository_Expecter) FindList(ctx interface{}, query interface{}) *MockRepository_FindList_Call {
	return &MockRepository_FindList_Call{Call: _e.mock.On("FindList", ctx, query)}
}

func (_c *MockRepository_FindList_Call) Run(run func(ctx context.Context, query attribute.ListQuery)) *MockRepository_FindList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 attribute.ListQuery
		if args[1] != nil {
			arg1 = args[1].(attribute.ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindList_Call) Return(pageResult *mongo.PageResult[attribute.Attribute], err error) *MockRepository_FindList_Call {
	_c.Call.Return(pageResult, err)
	return _c
}

func (_c *MockRepository_FindList_Call) RunAndReturn(run func(ctx context.Context, query attribute.ListQuery) (*mongo.PageResult[attribute.Attribute], error)) *MockRepository_FindList_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository) Insert(ctx context.Context, attribute1 *attribute.Attribute) error {
	ret := _mock.Called(ctx, attribute1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *attribute.Attribute) error); ok {
		r0 = returnFunc(ctx, attribute1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - attribute1 *attribute.Attribute
func (_e *MockRepository_Expecter) Insert(ctx interface{}, attribute1 interface{}) *MockRepository_Insert_Call {
	return &MockRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, attribute1)}
}

func (_c *MockRepository_Insert_Call) Run(run func(ctx context.Context, attribute1 *attribute.Attribute)) *MockRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *attribute.Attribute
		if args[1] != nil {
			arg1 = args[1].(*attribute.Attribute)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call) Return(err error) *MockRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, attribute1 *attribute.Attribute) error) *MockRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, attribute1 *attribute.Attribute) (*attribute.Attribute, error) {
	ret := _mock.Called(ctx, attribute1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *attribute.Attribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *attribute.Attribute) (*attribute.Attribute, error)); ok {
		return returnFunc(ctx, attribute1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *attribute.Attribute) *attribute.Attribute); ok {
		r0 = returnFunc(ctx, attribute1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*attribute.Attribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *attribute.Attribute) error); ok {
		r1 = returnFunc(ctx, attribute1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - attribute1 *attribute.Attribute
func (_e *MockRepository_Expecter) Update(ctx interface{}, attribute1 interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, attribute1)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, attribute1 *attribute.Attribute)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *attribute.Attribute
		if args[1] != nil {
			arg1 = args[1].(*attribute.Attribute)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(attribute11 *attribute.Attribute, err error) *MockRepository_Update_Call {
	_c.Call.Return(attribute11, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, attribute1 *attribute.Attribute) (*attribute.Attribute, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
