logger:
  level: "debug"
  development: true

mongo:
  host: "mongo"
  database: "catalog"
  replica-set: rs0

security:
  token:
    public-key: "eb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"
    service-token: "v4.public.eyJleHAiOiIyMDM2LTA0LTA3VDE1OjM5OjQ3KzAyOjAwIiwiaWF0IjoiMjAyNi0wNC0xMFQxNTozOTo0NyswMjowMCIsIm5iZiI6IjIwMjYtMDQtMTBUMTU6Mzk6NDcrMDI6MDAiLCJwZXJtaXNzaW9ucyI6WyJwcm9kdWN0czpyZWFkIiwiY2F0ZWdvcmllczpyZWFkIiwiYXR0cmlidXRlczpyZWFkIiwidGVuYW50czpyZWFkIl0sInJvbGUiOiJzZXJ2aWNlX2FjY291bnQiLCJzZXJ2aWNlX25hbWUiOiJjYXRhbG9nLXNlcnZpY2UiLCJzdWIiOiJzZXJ2aWNlOmNhdGFsb2ctc2VydmljZSIsInR5cGUiOiJhY2Nlc3MifZ_MytFEvw6znBwB97F36DA-Nxl1g7Vxw9mnkkCTcbMvGfGZJxlEh5Kvg5YYHm1t_7Bmw3GdDECYB8YV8d0QYQE"

kafka:
  brokers: "redpanda:29092"
  schema-registry:
    url: "http://redpanda:8081"
    auto-register-schemas: true
  consumers-config:
    default-group-id: "ecommerce-catalog-service"
    default-auto-offset-reset: "earliest"
    consumers:
      - name: "tenant-events"
        topic: "tenant.tenant.events"
        max-retries: 5
        initial-backoff: 2s
        max-backoff: 30s
        enable-dlq: true

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false

pprof:
  enabled: true
  port: 6060

clients:
  tenant-service:
    base-url: "http://ecommerce-tenant-service:8080"
