logger:
  level: "debug"
  development: true

mongo:
  host: "localhost"
  database: "catalog"
  direct-connection: true

kafka:
  brokers: "localhost:9092"

security:
  jwks:
    jwks-url: "http://localhost:3001/oidc/jwks"
    audience: "https://api.sokolshop.com"

observability:
  otel-collector-endpoint: ""
  tracing:
    enabled: true
  metrics:
    enabled: false