// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sokol111/ecommerce-catalog-service/internal/domain/category"
	"github.com/Sokol111/ecommerce-commons/pkg/messaging/patterns/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryEventFactory creates a new instance of MockCategoryEventFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryEventFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryEventFactory {
	mock := &MockCategoryEventFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryEventFactory is an autogenerated mock type for the CategoryEventFactory type
type MockCategoryEventFactory struct {
	mock.Mock
}

type MockCategoryEventFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryEventFactory) EXPECT() *MockCategoryEventFactory_Expecter {
	return &MockCategoryEventFactory_Expecter{mock: &_m.Mock}
}

// NewCategoryUpdatedOutboxMessage provides a mock function for the type MockCategoryEventFactory
func (_mock *MockCategoryEventFactory) NewCategoryUpdatedOutboxMessage(ctx context.Context, c *category.Category) outbox.Message {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for NewCategoryUpdatedOutboxMessage")
	}

	var r0 outbox.Message
	if returnFunc, ok := ret.Get(0).(func(context.Context, *category.Category) outbox.Message); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(outbox.Message)
	}
	return r0
}

// MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCategoryUpdatedOutboxMessage'
type MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call struct {
	*mock.Call
}

// NewCategoryUpdatedOutboxMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - c *category.Category
func (_e *MockCategoryEventFactory_Expecter) NewCategoryUpdatedOutboxMessage(ctx interface{}, c interface{}) *MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call {
	return &MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call{Call: _e.mock.On("NewCategoryUpdatedOutboxMessage", ctx, c)}
}

func (_c *MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call) Run(run func(ctx context.Context, c *category.Category)) *MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *category.Category
		if args[1] != nil {
			arg1 = args[1].(*category.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call) Return(message outbox.Message) *MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call) RunAndReturn(run func(ctx context.Context, c *category.Category) outbox.Message) *MockCategoryEventFactory_NewCategoryUpdatedOutboxMessage_Call {
	_c.Call.Return(run)
	return _c
}
