// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sokol111/ecommerce-catalog-service/internal/domain/attribute"
	"github.com/Sokol111/ecommerce-commons/pkg/messaging/patterns/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAttributeEventFactory creates a new instance of MockAttributeEventFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttributeEventFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttributeEventFactory {
	mock := &MockAttributeEventFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttributeEventFactory is an autogenerated mock type for the AttributeEventFactory type
type MockAttributeEventFactory struct {
	mock.Mock
}

type MockAttributeEventFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttributeEventFactory) EXPECT() *MockAttributeEventFactory_Expecter {
	return &MockAttributeEventFactory_Expecter{mock: &_m.Mock}
}

// NewAttributeUpdatedOutboxMessage provides a mock function for the type MockAttributeEventFactory
func (_mock *MockAttributeEventFactory) NewAttributeUpdatedOutboxMessage(ctx context.Context, a *attribute.Attribute) outbox.Message {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for NewAttributeUpdatedOutboxMessage")
	}

	var r0 outbox.Message
	if returnFunc, ok := ret.Get(0).(func(context.Context, *attribute.Attribute) outbox.Message); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Get(0).(outbox.Message)
	}
	return r0
}

// MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAttributeUpdatedOutboxMessage'
type MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call struct {
	*mock.Call
}

// NewAttributeUpdatedOutboxMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - a *attribute.Attribute
func (_e *MockAttributeEventFactory_Expecter) NewAttributeUpdatedOutboxMessage(ctx interface{}, a interface{}) *MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call {
	return &MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call{Call: _e.mock.On("NewAttributeUpdatedOutboxMessage", ctx, a)}
}

func (_c *MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call) Run(run func(ctx context.Context, a *attribute.Attribute)) *MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *attribute.Attribute
		if args[1] != nil {
			arg1 = args[1].(*attribute.Attribute)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call) Return(message outbox.Message) *MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call) RunAndReturn(run func(ctx context.Context, a *attribute.Attribute) outbox.Message) *MockAttributeEventFactory_NewAttributeUpdatedOutboxMessage_Call {
	_c.Call.Return(run)
	return _c
}
