// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sokol111/ecommerce-catalog-service/internal/domain/product"
	"github.com/Sokol111/ecommerce-commons/pkg/messaging/patterns/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductEventFactory creates a new instance of MockProductEventFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductEventFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductEventFactory {
	mock := &MockProductEventFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductEventFactory is an autogenerated mock type for the ProductEventFactory type
type MockProductEventFactory struct {
	mock.Mock
}

type MockProductEventFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductEventFactory) EXPECT() *MockProductEventFactory_Expecter {
	return &MockProductEventFactory_Expecter{mock: &_m.Mock}
}

// NewProductUpdatedOutboxMessage provides a mock function for the type MockProductEventFactory
func (_mock *MockProductEventFactory) NewProductUpdatedOutboxMessage(ctx context.Context, p *product.Product) outbox.Message {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for NewProductUpdatedOutboxMessage")
	}

	var r0 outbox.Message
	if returnFunc, ok := ret.Get(0).(func(context.Context, *product.Product) outbox.Message); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(outbox.Message)
	}
	return r0
}

// MockProductEventFactory_NewProductUpdatedOutboxMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewProductUpdatedOutboxMessage'
type MockProductEventFactory_NewProductUpdatedOutboxMessage_Call struct {
	*mock.Call
}

// NewProductUpdatedOutboxMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - p *product.Product
func (_e *MockProductEventFactory_Expecter) NewProductUpdatedOutboxMessage(ctx interface{}, p interface{}) *MockProductEventFactory_NewProductUpdatedOutboxMessage_Call {
	return &MockProductEventFactory_NewProductUpdatedOutboxMessage_Call{Call: _e.mock.On("NewProductUpdatedOutboxMessage", ctx, p)}
}

func (_c *MockProductEventFactory_NewProductUpdatedOutboxMessage_Call) Run(run func(ctx context.Context, p *product.Product)) *MockProductEventFactory_NewProductUpdatedOutboxMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *product.Product
		if args[1] != nil {
			arg1 = args[1].(*product.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductEventFactory_NewProductUpdatedOutboxMessage_Call) Return(message outbox.Message) *MockProductEventFactory_NewProductUpdatedOutboxMessage_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockProductEventFactory_NewProductUpdatedOutboxMessage_Call) RunAndReturn(run func(ctx context.Context, p *product.Product) outbox.Message) *MockProductEventFactory_NewProductUpdatedOutboxMessage_Call {
	_c.Call.Return(run)
	return _c
}
