// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// WithTransaction provides a mock function for the type MockTxManager
func (_mock *MockTxManager) WithTransaction(ctx context.Context, fn func(txCtx context.Context) (any, error)) (any, error) {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(txCtx context.Context) (any, error)) (any, error)); ok {
		return returnFunc(ctx, fn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(txCtx context.Context) (any, error)) any); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, func(txCtx context.Context) (any, error)) error); ok {
		r1 = returnFunc(ctx, fn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxManager_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockTxManager_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(txCtx context.Context) (any, error)
func (_e *MockTxManager_Expecter) WithTransaction(ctx interface{}, fn interface{}) *MockTxManager_WithTransaction_Call {
	return &MockTxManager_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockTxManager_WithTransaction_Call) Run(run func(ctx context.Context, fn func(txCtx context.Context) (any, error))) *MockTxManager_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(txCtx context.Context) (any, error)
		if args[1] != nil {
			arg1 = args[1].(func(txCtx context.Context) (any, error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_WithTransaction_Call) Return(v any, err error) *MockTxManager_WithTransaction_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTxManager_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(txCtx context.Context) (any, error)) (any, error)) *MockTxManager_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
