// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Sokol111/ecommerce-commons/pkg/messaging/patterns/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOutbox creates a new instance of MockOutbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutbox {
	mock := &MockOutbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutbox is an autogenerated mock type for the Outbox type
type MockOutbox struct {
	mock.Mock
}

type MockOutbox_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutbox) EXPECT() *MockOutbox_Expecter {
	return &MockOutbox_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOutbox
func (_mock *MockOutbox) Create(ctx context.Context, msg outbox.Message) (outbox.SendFunc, error) {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 outbox.SendFunc
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.Message) (outbox.SendFunc, error)); ok {
		return returnFunc(ctx, msg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.Message) outbox.SendFunc); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(outbox.SendFunc)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbox.Message) error); ok {
		r1 = returnFunc(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutbox_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOutbox_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - msg outbox.Message
func (_e *MockOutbox_Expecter) Create(ctx interface{}, msg interface{}) *MockOutbox_Create_Call {
	return &MockOutbox_Create_Call{Call: _e.mock.On("Create", ctx, msg)}
}

func (_c *MockOutbox_Create_Call) Run(run func(ctx context.Context, msg outbox.Message)) *MockOutbox_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbox.Message
		if args[1] != nil {
			arg1 = args[1].(outbox.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutbox_Create_Call) Return(sendFunc outbox.SendFunc, err error) *MockOutbox_Create_Call {
	_c.Call.Return(sendFunc, err)
	return _c
}

func (_c *MockOutbox_Create_Call) RunAndReturn(run func(ctx context.Context, msg outbox.Message) (outbox.SendFunc, error)) *MockOutbox_Create_Call {
	_c.Call.Return(run)
	return _c
}
